version: "3.1"

services:
  web:
    build: web/
    ports:
      - "3000:3000"
    restart: on-failure:10
    networks:
      - web
    depends_on:
      - api

  api:
    build: api/
    ports:
      - "8443:8443"
    restart: on-failure:10
    networks:
      - web
      - database
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DATABASE_USER
      MONGO_INITDB_ROOT_PASSWORD: $DATABASE_PASSWORD
    restart: always
    networks:
      - database

volumes:
  db_data:

networks:
  web: {}
  database: {}
  processors: {}
